name: produitsapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  drift: ^2.21.0
  flutter:
    sdk: flutter
  flutter_slidable: ^3.1.1
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  path: ^1.8.3
  sqlite3_flutter_libs: ^0.5.3
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  firebase_ui_auth: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  drift_dev: ^2.21.2
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
